### ISSUE TITLE
Adjusting the color of background and foreground

### ISSUE THREAD

**Issue by TheLearner23** [adobe/PIH#1]
I understand that your model primarily modifies the color of the foreground object by considering the color of the background image. Is there a way to achieve the opposite effect, where the color of the foreground object remains unchanged while adjusting the background color to match with it? Thanks.

**Comment by TheLearner23** [comment]
Following up on these questions. Thanks for your attention...

**Comment by mgharbi** [comment]
This should be feasible, by inverting the mask of the region where the transform is applied, i.e. mask -> 1-mask .
