### ISSUE TITLE
Request for Updated Link to Pre-Trained Model

### ISSUE THREAD

**Issue by cymoon59** [adobe/PIH#11]
Thank you for your work.

It seems that the link to the pre-trained model is unavailable. Could you provide an updated link or guide me on how to access the model? I’d really appreciate your help.

Thanks again!

Best regards.

**Comment by akshatd007** [comment]
Hi, are there any updates as to the model weights being provided. it would be a great help.

**Comment by ArmastusChen** [comment]
Same question here!

**Comment by hsinwu13** [comment]
Same question here!

**Comment by KeWang0622** [comment]
Thanks for your feedbacks and sorry for being late on this issue:
here is the updated model link:
https://drive.google.com/file/d/1seW8qSnaBOQ4_S9bQ4ThVOdeJGYJ-f74/view
thank you for your interests!

**Comment by cymoon59** [comment]
Thank you for sharing your awesome work!
