### ISSUE TITLE
size mismatch error

### ISSUE THREAD

**Issue by TheLearner23** [adobe/PIH#2]
Hello, I occasionally get this error message for some background images (format .png or .jpg) for the same foreground image. Can you give me some hint about why this happens?

RuntimeError: Given groups=1, weight of size [64, 7, 7, 7], expected input[1, 9, 512, 512] to have 7 channels, but got 9 channels instead

**Comment by mgharbi** [comment]
Perhaps some .png images contain an alpha channel and end up having 4 channels instead of the expected 3?
